### ISSUE TITLE
Human readable names for locations

### ISSUE THREAD

**Issue by kuzeko** [BONSAMURAIS/arborist#10]
Now data in https://github.com/BONSAMURAIS/arborist/blob/master/arborist/data/exiobase_location_uris.csv

does not contain human readable names.
For instance, what are `WA, WE, WF` etc?

https://github.com/BONSAMURAIS/arborist/blob/118a6f5d949142a0b7747698af312150b275fad7/arborist/data/exiobase_location_uris.csv#L45-L49

**Comment by konstantinstadler** [comment]
These are Rest of the World regions. You could use the country converter for converting it to spelled out names: https://github.com/konstantinstadler/country_converter

**Comment by agneta20** [comment]
WA- Rest of Asia Pacific
WL - Rest of America
WE- Rest of Europe
WF- Rest of Africa
WM- Rest of Middle East

**Comment by kuzeko** [comment]
I see, thanks.
I think it would be good to have them as `rdfs:label` when we output the RDF.
