### ISSUE TITLE
Problems to run arborist-cli 

### ISSUE THREAD

**Issue by agneta20** [BONSAMURAIS/arborist#13]
We installed arborist using pip, but when we ran arborist-cli regenerate <folder name> 
it shows the following error

`(bonsai) C:\Users\agneta>arborist-cli regenerate temp_arb
Traceback (most recent call last):
  File "c:\users\agneta\appdata\local\continuum\anaconda3\envs\bonsai\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\agneta\appdata\local\continuum\anaconda3\envs\bonsai\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\agneta\AppData\Local\Continuum\anaconda3\envs\bonsai\Scripts\arborist-cli.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'arborist.bin'`

Not sure what is the right way to make it work.

**Comment by tngTUDOR** [comment]
which exact version of arborist did you install ?

**Comment by tngTUDOR** [comment]
issue #9 should have solved this

**Comment by agneta20** [comment]
v 0.3

**Comment by mfastudillo** [comment]
I have the same problem when trying to run the `arborist-cli`. I don't have problems to run it as a library

**Comment by tngTUDOR** [comment]
So version .3 from pypi.org registry is not up to date with this repo (@cmutel ;) )
_but_ you can install using pip in local mode

Here is how I install using "pip " in local mode:
```
git clone git@github.com:BONSAMURAIS/arborist.git
cd arborist
pip install .
```

**Comment by tngTUDOR** [comment]
At a higher level, I think we should publish seamlessly on a single conda channel and have more "maintainers" to make automatic publishing of the packages from github repo.

**Comment by tngTUDOR** [comment]
@agneta20 I suggest you uninstall your current install of pip, and do as mentionned in https://github.com/BONSAMURAIS/arborist/issues/13#issuecomment-556095539
